module.exports = [{
    name: 'Lionel Messi', 
    dob: 'June 24, 1987', 
    nationality: 'Argentina',
    img: 'https://i.imgur.com/TvJyvzM.jpg?1',
    team: "Paris Saint-Germain", 
    position: 'Attack',
    number: '30', 
    stats: { 
        pase: '85',
        shot: '92',
        passing: '91',
        dribbling: '95',
        defense: '34',
        physical: '65',
        overall: '93'
    }, 
}, 
{ 
    name: 'Cristiano Ronaldo', 
    dob: 'Feburary 5, 1985', 
    nationality: 'Portugal', 
    img: 'https://i.imgur.com/287xbU0.jpg?1',
    team: 'Manchester United', 
    position: 'Attack', 
    number: '7', 
    stats: {
        pase: '87', 
        shot: '93',
        passing: '82', 
        dribbling: '88', 
        defense: '34', 
        physical: '75', 
        overall: '91'
    }, 
}, 
{ 
    name: 'Anssumane "Ansu" Fati Vieria', 
    dob: 'October 31, 2002', 
    nationality: 'Spain', 
    img: 'https://i.imgur.com/HWtourU.jpg?1', 
    team: 'FC Barcelona', 
    postion: 'Attack', 
    number: '10', 
    stats: {
        pace: '84', 
        shot: '70', 
        passing: '74', 
        dribbling: '80', 
        defense: '27', 
        physical: '75', 
        overall: '75', 
    }, 
}, 
]